"""
Alert/Warning API endpoints.
Human-in-the-loop warning workflow: AI generates draft → forecaster reviews → approves/dismisses.
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional
from datetime import datetime, timedelta
from uuid import uuid4

router = APIRouter(prefix="/alerts", tags=["alerts"])

# In-memory alert store (will migrate to Supabase when connected)
_alerts: dict[str, dict] = {}


class AlertCreate(BaseModel):
    title: str
    description: Optional[str] = None
    risk_level: str  # low, moderate, high, severe
    affected_districts: list[str] = []
    storm_cell_ids: list[str] = []
    valid_hours: int = 2
    evidence: Optional[dict] = None


class AlertReview(BaseModel):
    action: str  # approved, dismissed
    comment: Optional[str] = None


@router.get("")
async def list_alerts(status: Optional[str] = None):
    """List all alerts, optionally filtered by status."""
    alerts = list(_alerts.values())
    if status:
        alerts = [a for a in alerts if a["status"] == status]
    alerts.sort(key=lambda a: a["created_at"], reverse=True)
    return {"count": len(alerts), "alerts": alerts}


@router.get("/pending")
async def get_pending_alerts():
    """Get alerts pending forecaster review."""
    pending = [a for a in _alerts.values() if a["status"] == "pending_review"]
    pending.sort(key=lambda a: a["created_at"], reverse=True)
    return {"count": len(pending), "alerts": pending}


@router.post("")
async def create_alert(alert: AlertCreate):
    """Create a new alert (typically auto-generated by the risk engine)."""
    alert_id = str(uuid4())
    now = datetime.utcnow()

    alert_data = {
        "id": alert_id,
        "title": alert.title,
        "description": alert.description,
        "status": "pending_review",
        "risk_level": alert.risk_level,
        "affected_districts": alert.affected_districts,
        "storm_cell_ids": alert.storm_cell_ids,
        "valid_from": now.isoformat(),
        "valid_to": (now + timedelta(hours=alert.valid_hours)).isoformat(),
        "evidence": alert.evidence,
        "created_at": now.isoformat(),
        "updated_at": now.isoformat(),
        "reviews": [],
    }

    _alerts[alert_id] = alert_data
    return alert_data


@router.get("/{alert_id}")
async def get_alert(alert_id: str):
    """Get a specific alert by ID."""
    if alert_id not in _alerts:
        raise HTTPException(status_code=404, detail="Alert not found")
    return _alerts[alert_id]


@router.post("/{alert_id}/review")
async def review_alert(alert_id: str, review: AlertReview):
    """
    Review an alert — approve or dismiss.
    This is the human-in-the-loop step (CORE.md Section 5).
    """
    if alert_id not in _alerts:
        raise HTTPException(status_code=404, detail="Alert not found")

    alert = _alerts[alert_id]

    if alert["status"] not in ("pending_review", "draft"):
        raise HTTPException(
            status_code=400,
            detail=f"Alert cannot be reviewed in status: {alert['status']}"
        )

    if review.action not in ("approved", "dismissed"):
        raise HTTPException(
            status_code=400,
            detail="Action must be 'approved' or 'dismissed'"
        )

    now = datetime.utcnow()
    alert["status"] = review.action
    alert["updated_at"] = now.isoformat()
    alert["reviews"].append({
        "action": review.action,
        "comment": review.comment,
        "reviewed_at": now.isoformat(),
    })

    return alert


def auto_generate_alert(storm: dict, risk: dict) -> Optional[dict]:
    """
    Automatically generate a warning draft when risk exceeds thresholds.
    Called by the pipeline after risk assessment.
    Returns the created alert or None if risk is below threshold.
    """
    if risk["risk_level"] not in ("high", "severe"):
        return None

    alert = AlertCreate(
        title=f"Thunderstorm Warning — {storm.get('cell_id', 'Unknown')}",
        description=(
            f"Storm cell {storm.get('cell_id')} detected with {risk['risk_level'].upper()} risk. "
            f"Moving {risk.get('direction_deg', 0):.0f}° at {risk.get('speed_kmh', 0):.0f} km/h. "
            f"Thunderstorm probability: {risk['thunderstorm_probability']:.0%}. "
            f"Lightning probability: {risk['lightning_probability']:.0%}."
        ),
        risk_level=risk["risk_level"],
        storm_cell_ids=[storm.get("cell_id", "")],
        evidence={
            "thunderstorm_probability": risk["thunderstorm_probability"],
            "lightning_probability": risk["lightning_probability"],
            "intensity": risk["intensity"],
            "speed_kmh": risk["speed_kmh"],
            "trend": risk["trend"],
        },
    )

    # Check if we already have a pending alert for this cell
    for existing in _alerts.values():
        if (
            existing["status"] == "pending_review"
            and storm.get("cell_id") in existing.get("storm_cell_ids", [])
        ):
            return None  # Don't duplicate

    import asyncio
    return asyncio.get_event_loop().run_until_complete(create_alert(alert))
